apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard-service

spec:
  type: LoadBalancer    # no LB ( kubeadm installation ) LB == NodePort
  externalIPs:
    - 192.168.0.109
  ports:
    - port: 8080
      targetPort: dashboard
  selector:
    app: traefik
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-web-service

spec:
  type: LoadBalancer    # no LB ( kubeadm installation ) LB == NodePort
  externalIPs:
    - 192.168.0.110
  ports:
    - targetPort: web
      port: 80
  selector:
    app: traefik
